# -*- coding: utf-8 -*-
"""Day11-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xkvPXyhMsIRT6_Zg_OyBqQIsokb57Dx7
"""

import pip
!pip install pandas

!pip install pandas

!pip uninstall pandas